/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package textanalyzer;

/**
 *
 * @author nikhilnarwade
 */
public class TextAnalyzerFrame extends javax.swing.JFrame {

    /**
     * Creates new form TextAnalyzerFrame
     */
    public TextAnalyzerFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        lengthField = new javax.swing.JTextField();
        length = new javax.swing.JTextField();
        wordsField = new javax.swing.JTextField();
        words = new javax.swing.JTextField();
        spacesField = new javax.swing.JTextField();
        spaces = new javax.swing.JTextField();
        linesField = new javax.swing.JTextField();
        lines = new javax.swing.JTextField();
        tabsField = new javax.swing.JTextField();
        tabs = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        charCountField = new javax.swing.JTextField();
        charCount = new javax.swing.JTextField();
        dropDown = new javax.swing.JComboBox<>();
        wordCountField = new javax.swing.JTextField();
        getCount = new javax.swing.JButton();
        wordCount = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setBackground(new java.awt.Color(255, 255, 153));
        jLabel2.setFont(new java.awt.Font("AkayaKanadaka", 1, 22)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Text Analyzer");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Submit.setBackground(new java.awt.Color(255, 204, 204));
        Submit.setFont(new java.awt.Font("AkayaKanadaka", 1, 18)); // NOI18N
        Submit.setForeground(new java.awt.Color(51, 51, 51));
        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        jTextPane1.setBackground(new java.awt.Color(204, 255, 255));
        jScrollPane1.setViewportView(jTextPane1);

        lengthField.setBackground(new java.awt.Color(204, 255, 204));
        lengthField.setFont(new java.awt.Font("AkayaKanadaka", 1, 18)); // NOI18N
        lengthField.setText("Text Length");
        lengthField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lengthFieldActionPerformed(evt);
            }
        });

        length.setEditable(false);
        length.setBackground(new java.awt.Color(255, 204, 255));
        length.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        wordsField.setBackground(new java.awt.Color(204, 255, 204));
        wordsField.setFont(new java.awt.Font("AkayaKanadaka", 0, 18)); // NOI18N
        wordsField.setText("Words Count");
        wordsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wordsFieldActionPerformed(evt);
            }
        });

        words.setEditable(false);
        words.setBackground(new java.awt.Color(255, 204, 255));
        words.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        spacesField.setEditable(false);
        spacesField.setBackground(new java.awt.Color(204, 255, 204));
        spacesField.setFont(new java.awt.Font("AkayaKanadaka", 0, 18)); // NOI18N
        spacesField.setText("Space Count");
        spacesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spacesFieldActionPerformed(evt);
            }
        });

        spaces.setEditable(false);
        spaces.setBackground(new java.awt.Color(255, 204, 255));
        spaces.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        linesField.setEditable(false);
        linesField.setBackground(new java.awt.Color(204, 255, 204));
        linesField.setFont(new java.awt.Font("AkayaKanadaka", 0, 18)); // NOI18N
        linesField.setText("Lines Count");
        linesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linesFieldActionPerformed(evt);
            }
        });

        lines.setEditable(false);
        lines.setBackground(new java.awt.Color(255, 204, 255));
        lines.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tabsField.setEditable(false);
        tabsField.setBackground(new java.awt.Color(204, 255, 204));
        tabsField.setFont(new java.awt.Font("AkayaKanadaka", 0, 18)); // NOI18N
        tabsField.setText("Tabs Count");
        tabsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabsFieldActionPerformed(evt);
            }
        });

        tabs.setEditable(false);
        tabs.setBackground(new java.awt.Color(255, 204, 255));
        tabs.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        charCountField.setEditable(false);
        charCountField.setBackground(new java.awt.Color(204, 204, 204));
        charCountField.setFont(new java.awt.Font("AkayaKanadaka", 0, 18)); // NOI18N
        charCountField.setText("Character count");

        charCount.setBackground(new java.awt.Color(204, 204, 204));
        charCount.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dropDown.setBackground(new java.awt.Color(204, 204, 204));
        dropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropDownActionPerformed(evt);
            }
        });

        wordCountField.setBackground(new java.awt.Color(204, 204, 204));
        wordCountField.setFont(new java.awt.Font("AkayaKanadaka", 0, 18)); // NOI18N
        wordCountField.setText("Enter word");

        getCount.setBackground(new java.awt.Color(204, 204, 204));
        getCount.setFont(new java.awt.Font("AkayaKanadaka", 0, 13)); // NOI18N
        getCount.setText("Get Count");
        getCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getCountActionPerformed(evt);
            }
        });

        wordCount.setBackground(new java.awt.Color(204, 204, 204));
        wordCount.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(153, 153, 255));
        jTextField1.setFont(new java.awt.Font("AkayaKanadaka", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Specific Count");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(spacesField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lengthField)
                                            .addComponent(linesField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tabsField, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(length, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(spaces, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lines, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(charCountField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(charCount, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(wordsField)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(words, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(wordCountField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(getCount, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wordCount, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lengthField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(length, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(words, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wordsField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spacesField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spaces, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(linesField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lines, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tabsField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(charCountField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(charCount, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wordCount, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(wordCountField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(getCount, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Submit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        TextAnalyzer t = new TextAnalyzer(jTextPane1.getText());
        length.setText(t.getLength());
        words.setText(t.getWords());
        spaces.setText(t.getSpaces());
        lines.setText(t.getLines());
        tabs.setText(t.getTabs());
        dropDown.setModel(t.getModel());
        
        
    }//GEN-LAST:event_SubmitActionPerformed

    private void getCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getCountActionPerformed
        // TODO add your handling code here:
        TextAnalyzer t = new TextAnalyzer(jTextPane1.getText());
        wordCount.setText(t.getWordCount(wordCountField.getText()));
        charCount.setText(t.getCharCount(dropDown.getItemAt(dropDown.getSelectedIndex())));
    }//GEN-LAST:event_getCountActionPerformed

    private void lengthFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lengthFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lengthFieldActionPerformed

    private void spacesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spacesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spacesFieldActionPerformed

    private void linesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linesFieldActionPerformed

    private void tabsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabsFieldActionPerformed

    private void wordsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wordsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wordsFieldActionPerformed

    private void dropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropDownActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TextAnalyzerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TextAnalyzerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TextAnalyzerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TextAnalyzerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TextAnalyzerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Submit;
    private javax.swing.JTextField charCount;
    private javax.swing.JTextField charCountField;
    private javax.swing.JComboBox<String> dropDown;
    private javax.swing.JButton getCount;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField length;
    private javax.swing.JTextField lengthField;
    private javax.swing.JTextField lines;
    private javax.swing.JTextField linesField;
    private javax.swing.JTextField spaces;
    private javax.swing.JTextField spacesField;
    private javax.swing.JTextField tabs;
    private javax.swing.JTextField tabsField;
    private javax.swing.JTextField wordCount;
    private javax.swing.JTextField wordCountField;
    private javax.swing.JTextField words;
    private javax.swing.JTextField wordsField;
    // End of variables declaration//GEN-END:variables
}
